# Julia Abdel-Monem, 2025
# Polymorphic Games


extends EditorInspectorPlugin

func _can_handle(object: Object) -> bool:

	return object is InkResource and not object is InkResourceSet

# returns 0 if it should do nothing, 1 if it should nest, 2 if it should return to parent
func handle_node(node: InkNode, root: TreeItem, path: String):
	if node is InkContainer:
		handle_container(node, root, path)
		root.set_metadata(0, path)
		root.set_selectable(0, true)
	elif node is InkString:
		root.set_text(0, "%s '%s'" % [root.get_text(0), node.value])
		root.set_selectable(0, false)
	elif node is InkCommand:

		root.set_text(0, "%s $('%s')" % [root.get_text(0), node.command])
		root.set_selectable(0, false)
		if node.command == "#" or node.command == "ev" or node.command == "str":
			return 1
		elif node.command[0] == "/":
			return 2

	elif node is InkDivert:
		root.set_text(0, "%s -> %s" % [root.get_text(0), node.path])
		root.set_selectable(0, false)
	elif node is InkChoicePoint:
		root.set_text(0, "%s Choice -> %s" % [root.get_text(0), node.path])
		root.set_selectable(0, false)
	return 0

func handle_container(container: InkContainer, root: TreeItem, path: String):


	if container.arr.size() > 0:
		var arr = root.create_child()
		arr.collapsed = true
		arr.set_selectable(0, false)
		var counter = 0
		for x in container.arr:
			var child = arr.create_child()

			child.set_text(0, "%d:" % [counter])
			child.collapsed = true
			var out = handle_node(x, child, (path + '.%d' % counter) if path != '' else ('%d' % counter))

			if out == 1:
				arr = child
			elif out == 2:
				arr = arr.get_parent()

			counter += 1

		arr.set_text(0, "Array (size: %d)" % container.arr.size())

	if container.dict.keys().size() > 0:
		var dict = root.create_child()
		dict.set_selectable(0, false)
		for x in container.dict.keys():
			var child = dict.create_child()
			child.set_text(0, x)
			child.collapsed = true
			handle_node(container.dict[x], child, (path + '.%s' % x) if path != '' else x)

		dict.collapsed = true
		dict.set_text(0, "Dictionary (size: %d)" % container.dict.keys().size())

var tree: Tree = null

var handle_as_tag = false

func gettext_handle_node(item: InkNode, text_edit: TextEdit, index: String, path_str: String):

	if item is InkString:
		if handle_as_tag:
			text_edit.text += '# %s\n' % [item.value]
		else:
			text_edit.text += '# %s.%s\n' % [path_str, index]
			text_edit.text += 'msgid "%s"\nmsgstr ""\n' % [item.value]


	elif item is InkCommand:
		if item.command == '#':
			handle_as_tag = true
		elif item.command == '/#':
			handle_as_tag = false
		elif (item.command == 'newline' or item.command == '/ev'):
			text_edit.text += '\n'

	elif item is InkContainer:

		iterate_container(item, text_edit, '%s%s' % [path_str + '.' if path_str != "" else "", index])


func iterate_container(container: InkContainer, text_edit: TextEdit, path_str: String):
	var counter = 0

	# var is_ink_string = func (x) -> bool:
	# 	return x is InkString


	for item in container.arr:
		gettext_handle_node(item, text_edit, '%s' % counter, path_str)
		counter += 1


	for key in container.dict.keys():
		var item = container.dict[key]
		gettext_handle_node(item, text_edit, key, path_str)


func _parse_begin(object: Object) -> void:
	tree = Tree.new()
	tree.custom_minimum_size = Vector2(-1, 300)
	var root = tree.create_item()
	tree.hide_root = true
	tree.columns = 1
	tree.allow_rmb_select = true

	var container: InkContainer = object.root

	handle_node(container, root, '')

	tree.gui_input.connect(tree_input)

	add_custom_control(tree)

	var text_edit: TextEdit = TextEdit.new()
	text_edit.text = '# autogenerated gettext file\n# generated by polymorphic.ink v1.0\n# do not remove the next two lines\nmsgid ""\nmsgstr ""\n\n'
	text_edit.editable = false

	text_edit.custom_minimum_size = Vector2(-1, 300)

	iterate_container(container, text_edit, "")

	add_custom_control(text_edit)


func copy_path():
	var path = tree.get_selected().get_metadata(0)
	if path != null:
		print('copying path %s' % path)
		DisplayServer.clipboard_set(String(path))


func popup_id_pressed(id: int):
	if id == 0:
		copy_path()

func tree_input(event: InputEvent):
	if tree != null and event is InputEventMouseButton:
		if event.button_index == MOUSE_BUTTON_RIGHT and event.is_pressed():

			var node = tree.get_item_at_position(event.position)

			if node.is_selectable(0):
				tree.set_selected(node, 0)
				var path = tree.get_selected().get_metadata(0)
				if path != null:
					var popup_menu = PopupMenu.new()
					popup_menu.add_item("Copy Path")

					# print(tree.get_local_mouse_position())

					tree.add_child(popup_menu)

					popup_menu.id_pressed.connect(popup_id_pressed)
					popup_menu.always_on_top = true
					popup_menu.position = tree.get_global_mouse_position()
					popup_menu.visible = true
					popup_menu.max_size = Vector2(120, 50)
